{
 "title": "Custom Exporter",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "city",
    "label": "City",
    "query": {
     "query": "label_values(weather_temperature_celsius,city)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Min Humidity",
   "type": "gauge",
   "description": "Минимальная влажность",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(weather_humidity_percent{country=\"Kazakhstan\", city=~\"$city\"}) by (country)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max Wind Speed",
   "type": "gauge",
   "description": "Максимальная скорость ветра",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(weather_windspeed_kmh{country=\"Kazakhstan\", city=~\"$city\"}) by (country)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg Temperature in Country",
   "type": "gauge",
   "description": "Средняя температура по стране",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(weather_temperature_celsius{country=\"Kazakhstan\", city=~\"$city\"}) by (country)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total API Calls",
   "type": "gauge",
   "description": "Количество успешных вызовов API",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "weather_api_calls_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "API Response Time",
   "type": "gauge",
   "description": "Время отклика API",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "weather_api_response_time_seconds",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cloud Cover",
   "type": "gauge",
   "description": "Облачность в %",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "weather_cloudcover_percent{country=\"Kazakhstan\", city=~\"$city\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Precipitation (Rain 1h)",
   "type": "timeseries",
   "description": "Осадки за последний час",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "weather_precipitation_mm{country=\"Kazakhstan\", city=~\"$city\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Air Pressure",
   "type": "timeseries",
   "description": "Давление в гПа",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "weather_pressure_hpa{country=\"Kazakhstan\", city=~\"$city\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "description": "Влажность воздуха",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "targets": [
    {
     "expr": "weather_humidity_percent{country=\"Kazakhstan\", city=~\"$city\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Wind Speed",
   "type": "timeseries",
   "description": "Скорость ветра по городам",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "targets": [
    {
     "expr": "weather_windspeed_kmh{country=\"Kazakhstan\", city=~\"$city\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Feels Like Temp",
   "type": "gauge",
   "description": "Ощущаемая температура",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 80 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "weather_temperature_max_celsius{country=\"Kazakhstan\", city=~\"$city\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Temperature",
   "type": "gauge",
   "description": "Температура по городам",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 88 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "weather_temperature_celsius{country=\"Kazakhstan\", city=~\"$city\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}