{
 "title": "Database Exporter",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "db",
    "label": "Database",
    "query": {
     "query": "label_values(pg_stat_activity_count,datname)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Top 10 таблиц по строкам",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, sum by(relname)(pg_user_tables_rows_rows_estimated))\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg Rows per Table",
   "type": "gauge",
   "description": "Среднее количество строк в таблицах",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(pg_user_tables_rows_rows_estimated)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total active connections",
   "type": "gauge",
   "description": "Общее количество активных подключений",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(pg_stat_activity_count)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "DB Size (bytes)",
   "type": "gauge",
   "description": "Размер базы данных в байтах",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pg_database_size_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "QPS (queries/sec)",
   "type": "timeseries",
   "description": "Скорость обработки запросов",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sum(rate(pg_stat_database_xact_commit[5m]) + rate(pg_stat_database_xact_rollback[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Commits by DB",
   "type": "heatmap",
   "description": "Активность по базам",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "sum by (datname)(pg_stat_database_xact_commit)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Users",
   "type": "stat",
   "description": "Количество пользователей",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(pg_roles_list_dummy_value)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rollbacks per 5m",
   "type": "timeseries",
   "description": "Ошибки/откаты",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "rate(pg_stat_database_xact_rollback[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Commits per 5m",
   "type": "timeseries",
   "description": "Активность коммитов",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "targets": [
    {
     "expr": "rate(pg_stat_database_xact_commit[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connections by DB",
   "type": "timeseries",
   "description": "Подключения по базам",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "targets": [
    {
     "expr": "count by(datname)(pg_stat_activity_count{datname=~\"$db\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}