{
 "title": "Node Exporter",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "device",
    "label": "Network Device",
    "query": {
     "query": "label_values(node_network_receive_bytes_total,device)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Number of Block Devices",
   "type": "gauge",
   "description": "Количество активных операций ввода-вывода на всех устройствах.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(node_disk_io_now)\r\n", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Swap Usage Memory",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_SwapTotal_bytes - node_memory_SwapFree_bytes",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "System Uptime",
   "type": "gauge",
   "description": "Время работы системы в секундах",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds - node_boot_time_seconds",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Processes",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(node_procs_running)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Network Outgoing (Mbit/s)",
   "type": "timeseries",
   "description": "Исходящий трафик в Mbit/sec",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{device=~\"$device\"}[5m]) * 8 / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Incoming (Mbit/s)",
   "type": "timeseries",
   "description": "Входящий трафик в Mbit/sec",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{device=~\"$device\"}[5m]) * 8 / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Free Memory (GB)",
   "type": "gauge",
   "description": "Свободная память в GB",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemAvailable_bytes / 1024 / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM Usage %",
   "type": "gauge",
   "description": "Процент занятой памяти",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Load Average 5m",
   "type": "gauge",
   "description": "Средняя нагрузка за 5 минут",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_load5", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Load Average 1m",
   "type": "gauge",
   "description": "Средняя нагрузка за 1 минуту",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_load1", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total CPU Usage",
   "type": "gauge",
   "description": "Общая загрузка процессора в процентах",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 80 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg(rate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage per Core",
   "type": "timeseries",
   "description": "Использует rate() для вычисления использования CPU по ядрам",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 88 },
   "targets": [
    {
     "expr": "avg(rate(node_cpu_seconds_total{mode!=\"idle\"}[5m])) by (cpu)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}